--!strict

require("DesertEagle_Customization")
require("DesertEagle_Gunsway")
require("DesertEagle")

require("FN57_Customization")
require("FN57_Gunsway")
require("FN57")

require("Glock18_Customization")
require("Glock18_Gunsway")
require("Glock18")

require("HK45C_Customization")
require("HK45C_Gunsway")
require("HK45C")

require("M93R_Customization")
require("M93R_Gunsway")
require("M93R")

require("P226_Customization")
require("P226_GunSway")
require("P226")

require("SW40_Gunsway")
require("SW40")

require("Taurus_Gunsway")
require("Taurus44_Customization")
require("Taurus44")

return nil
